<?php include "header.php" ?>
<?php include "slider.php" ?>
<?php include "overview.php" ?>
<?php include "offer.php" ?>
<?php include "studentcount.php" ?>
<?php include "programs.php" ?>
<?php include "testi.php" ?>
<?php include "ourstaff.php" ?>
<?php include "footer.php" ?>